// Copyright(C) 1999-2005 LiuTaoTao£¬bookaa@rorsoft.com

#include "windows.h"
//#include <afxtempl.h>
#include    <assert.h>

#include	<stdio.h>
#include	"dasm.h"
#include	"mylist.h"
#include	"standard.h"
#include	"enum.h"
#include	"CApiManage.h"
#include	"fileload.h"

#include	"EXPR.h"
#include	"INSTR.h"
#include	"ComplexInstr.h"
#include	"CFunc.h"
#include	"CCodeList.h"
#include	"CExprManage.h"
#include	"CNameID.h"

#include	"proto.h"


